### PR TITLE
feat: 🎸 (deps) update svg-to-ts to v7

### PR DESCRIPTION
**Pull request by ChazUK**
BREAKING CHANGE: 🧨 Update svg-to-ts to v7

### CODE REVIEW

**Comment by ChazUK** [comment]
This is a fix for https://github.com/angular-extensions/svg-icons-builder/issues/29

@kreuzerk can you please give it a look over.

**Review by nivekcode — APPROVED** [review]

**Comment by nivekcode** [comment]
@ChazUK looks good. Thx a lot for this PR!

**Comment by nivekcode** [comment]
@all-contributors please add @ChazUK  for code

**Pull request merged**
